### ISSUE TITLE
SVG Code makes constraint disappear on removing a circle.

### ISSUE THREAD

**Issue by Brawlboxgaming** [Timwi/Zinga#4]
After removing the circle from this constraint, if the cells are set to a straight line of any fashion, the SVG disappears either when selected, or when violated on the test page.

```
"<g opacity='.2'>
<path d='M{{c: " {c.cx} {c.cy}"}}' stroke='black' stroke-width='.3' stroke-linecap='round' stroke-linejoin='round' fill='none' />
<circle cx='{{c first: c.cx}}' cy='{{c first: c.cy}}' r='.4' fill='black' opacity='0'/>
</g>"
```

**Comment by Timwi** [comment]
Thanks for reporting! The issue was with the SVG filter that renders the highlighting. That’s fixed now.
