### ISSUE TITLE
Sandwich and X-Sum Constraint causes errors in console.

### ISSUE THREAD

**Issue by Brawlboxgaming** [Timwi/Zinga#8]
![image](https://user-images.githubusercontent.com/71042104/116997096-42e0b900-acd4-11eb-8f57-573cb1b5f703.png)

This happens when making a sandwich or x-sum constraint of any variety.

**Comment by Timwi** [comment]
Thanks for the report! Fixed in a0958e76c9043014551b1104ad8e05ffa0ea7d90.
